language: python
python:
  - "2.7"
  - "3.4"
env:
  - DJANGO=1.7.4
install:
  - pip install -e . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - coverage run runtests.py
  - coverage report -m
after_success:
  - coveralls --verbose
